### ISSUE TITLE
Prepend VTM_ to all dict names in patches

### ISSUE THREAD

**Issue by eirikblekesaune** [eirikblekesaune/VTMax#10]

**Comment by eirikblekesaune** [comment]
Update dict names in javascript code accordingly

**Comment by balintlaczko** [comment]
The only "threat" was in [dict scenes], and that got renamed (and rereferenced) as [dict VTM_scenes]. Since the unnamed ones have randomly generated names and they are cleared before each contact, it's not necessary to rename them.
