### ISSUE TITLE
Integrate MenuBar functionality into VTMGlobal

### ISSUE THREAD

**Issue by salkin-mada** [eirikblekesaune/VTMax#15]
When opening VTMGlobal a menu entry should appear.
This could hold shortcuts, so to say, to Important "superuser" subpatchers etc. i.e. p cores, vtmglobal patch and so on.

**Comment by magnusbugge** [comment]
Would be really cool, but it does not seem possible without sacrificing the rest of the menu items in max. Now using text buttons instead.
