### ISSUE TITLE
SpatProxy model -> msp connections to the model is removed.

### ISSUE THREAD

**Issue by salkin-mada** [eirikblekesaune/VTMax#18]
inside a scene core -> connect msp signal to a spatProxy.model and save -> then close scene.
open scene, go to core. happy happy, no connections to the spatProxy

**Comment by magnusbugge** [comment]
Interesting. Maybe relates to that I am currently not able to create spatProxy.models with a defined number of channels, only getting the first inlet.

**Comment by balintlaczko** [comment]
Really? I just tried to reproduce this, but it seems to work. You mean in the actual core of the scene, not in the generic SceneCore.model, right? I made a noise~ going to a VTMSpatProxy.model and then saved, closed, opened, it's still there. Did I miss something?

**Comment by balintlaczko** [comment]
Wait I am sure I have missed something, for me it seems that it doesn't make sense to connect audio to the VTMSpatProxy.model since that inlet is only for interfacing with the j.model, ikke sant?

**Comment by salkin-mada** [comment]
Lets fix this by using mc.
Instead of the old VT js solution where we default max channels and remove the correct amount.
The problem as of now stems from the javascript.
