### ISSUE TITLE
Change client setup menu in VTMGlobal to select user configuration instead

### ISSUE THREAD

**Issue by eirikblekesaune** [eirikblekesaune/VTMax#19]
Let all IP and hostname stuff be selected by the zeroconf functionality.
Selecting client setup only causes loading a setup patch.

**Comment by eirikblekesaune** [comment]
The client setup also sets the channels for the spat allocatorChannels. This means that the lydserer proxy is not initialized until a client setup has been chosen.

**Comment by salkin-mada** [comment]
fixed
