### ISSUE TITLE
midi device connect and VTMGlobal configuration load order

### ISSUE THREAD

**Issue by salkin-mada** [eirikblekesaune/VTMax#36]
if a midi device is connected after the configuration file have been loaded. 
midi device is not sending to VTMGlobal.
possibly a bug in MIDIMIX, i.e. not a general problem.
maybe a midi object programmer responsibility.
https://github.com/blacksound/VTMax/tree/master/patchers/ImportedFrom_vt_max/MIDIControllers/MIDIMIX

**Comment by balintlaczko** [comment]
https://github.com/blacksound/VTMax/tree/master/patchers/ImportedFrom_vt_max/MIDIControllers/MIDIMIX

**Comment by magnusbugge** [comment]
This has been solved in the following way:

MIDI Mix patcher now updated using 'midiinfo' object with the argument '@autopollcontrollers 1', connected to the 'midiin' object. This will always keep the list of controllers up tp date even if reconnecting midi devices and switching usb ports.
