### ISSUE TITLE
VTMSpatProxy.view destination shows 'none' after server reboot and re-activating scene on a spat proxy with a valid destination

### ISSUE THREAD

**Issue by salkin-mada** [eirikblekesaune/VTMax#54]
but only if the client was init before the VTLydserver was running

**Comment by salkin-mada** [comment]
this is a text display bug
if a client has activated a scene with a spat proxy and via the spat proxy view has selected and queried a spat module from the server with the destination of for an example 'genelec.3' and the server then reboots, the spat proxy view correctly instantly turns red. i.e no module present at the server for this spat proxy. When the client then re-activates the scene the spat proxy correctly then again asks the server to build one spat module for it with the destination of 'genelec.3'. this then happens and then spat proxy view turns green to indicate that there now again is a spat module present at the server. BUT the spat proxy view shows 'none' in the destination name, nevertheless the destination being 'genelec.3'

**Comment by balintlaczko** [comment]
it's not just green, but behind 'none' is actually gogo, so when server reboots the display doesn't get the destination again

**Comment by salkin-mada** [comment]
this still seems to be a problem. if a spat was set to `pa` and the server is rebooted, and the scene is re-activated. the view will default to none but be green hence ze module at the VTLydserver, it actually represents or communicates with, is build with the busnums of the `pa` group. and all is "good"

**Comment by balintlaczko** [comment]
grrrr. I don't remember the flow of info perfectly. Is it doing it when the server is rebooted (and it's resending the dest. sets), or when you reactivate the scene? Also I don't remember what was our "policy": whne the server reboots, should everything go to "none" and disconnect, or things should return the way they were? I guess the latter is more convenient. If I remember well, the change filter we put in place is preventing to clear and repopulate the umenu. So unless the set is somehow different, it should not do anything. We should look for what else is being sent from the server, and where does it reset the umenu to the first elem ("none").

**Comment by eirikblekesaune** [comment]
One way to go here is to ask yourselves: What does the color green signify?

IMO it should signify that a spat module is running on the lydserver. To
attain this, the color change should be mapped to the running state of the
SpatModule after said module is running, i.e. /spatModule.1/state ==
'running'. Not the fact that the destination parameter on the spat client
is not 'none'. The latter may be the case irregardless of the lydserver
running at all.

This mapping of semantics solves the problem of whether the color should be
green, as it only means one thing, and one thing only: There is a
corresponding spat module running on the lydserver. If that is the case,
the menu should be green. In any other case it is not. From this is is easy
to infer what will happen when the lydserer reboot and quits => all modules
have stopped running, i.e. => all modules.state != running => all
destination menus should not be green.

+Eirik

**Comment by salkin-mada** [comment]
Yes it is green after server reboot and the client reactivating the scene. 
Because a module is now again present, there is a module running at the server. 
it was build, correctly and all is good.
Color is not the issue, it is working correctly. The bug is the text switching to 'none' instead of staying at 'genelec' as an example. It is just that the spat view shows 'none' instead of the destination of the correctly freshly build spat module.
_Will change the name of the issue._

**Comment by eirikblekesaune** [comment]
Hmm, I do think that my point with regards to color and what it signifies
still stands though. At least worth considering. As of now the condition
that turns it green is:
state == 'running' && destination != 'none' //looking at [p
controlViewColorCueToStateChanges]

Removing the latter condition would attain what I would propose. It also
makes the functionality of said subpatcher less ambiguous, e.g. sending the
value from the [j.lazyReceive destionation] object into the subpatcher,
only to bang another j.lazyReceive inside it, that does the exact same
thing. I mean, its called 'controlViewColorCue*ToStateChanges*' for a
specific reason, no?

+Eirik

**Comment by salkin-mada** [comment]
mos def.

reconsidered and will do, good thoughts.

will look into it. thanks.

**Comment by salkin-mada** [comment]
we are no longer able to reproduce this. reopen if needed / if bug reoccurs . happy happy
