### ISSUE TITLE
double clicking to refresh Network Device does not fulfil a full VTMGlobal start up 

### ISSUE THREAD

**Issue by salkin-mada** [eirikblekesaune/VTMax#55]
this introduces a bug if the client opens `VTMGlobal` without being on the `1.2.3` network. 
The user then changes network connection to the `1.2.3 `network and in good faith, double clicks on the Network Device UI box, to reconnect and query destinations etc. The result is a client not able to connect and talk to the server (no client connect, no modules queries, no destinationSets and no running update) until the user re opens `VTMGlobal`

**Comment by balintlaczko** [comment]
It does, maaan

**Comment by salkin-mada** [comment]
indeed man
