### ISSUE TITLE
changing Network Device in VTMGlobal does not update ip

### ISSUE THREAD

**Issue by salkin-mada** [eirikblekesaune/VTMax#59]
If a client with wifi and thunderbolt/ethernet opens VTMGlobal and wifi is auto selected (with ip `1.2.3.248`) -> client then chooses thunderbolt/ethernet (with ip `1.2.3.88`) server and proxy still tries to communicate on `1.2.3.248` and the client has no contact with build spat modules.

**Comment by salkin-mada** [comment]
in addition the server does not free the old 1.2.3.248 modules when a client with same hostname on a new ip connects. this results in several modules on the server with the same name `'/magnusmbp/spat/tree_stereoOut3'` that outputs on fx. different destinations if the spat was build with (`'/destination/pa'` as an example). the client no longer has any control over the old spat module also named `'/magnusmbp/spat/tree_stereoOut3'`. and this module will continue to grab sound from the specified input busses and send it to the output busses (`'/destination/sub'`).
== sound always in pa and sub. changing the destination on the `VTMspatProxy.view` yields no control. sound will be spat in 2 destinations.

**Comment by balintlaczko** [comment]
could not reproduce it
