### ISSUE TITLE
Network Device refreshing-strangeness in Global

### ISSUE THREAD

**Issue by magnusbugge** [eirikblekesaune/VTMax#61]
VTMGlobal: Double clicking on Network Devices will fix issue of global not connecting to system (maybe not getting a correct list of devices?). On some computers there are some unknown hick-ups going on in this part of the global, should be cleared up.

**Comment by salkin-mada** [comment]
Could this be elaborated? What are these hickups? Is it related to the Apple Macintosh Network order of service list?

**Comment by salkin-mada** [comment]
will reopen if network device service order plays any role in this matter. but for now we are not able to detect any strangeness :)
