### ISSUE TITLE
write cue pop up window should have "YES" button selected by default

### ISSUE THREAD

**Issue by salkin-mada** [eirikblekesaune/VTMax#62]
then we don't have to move the mouse to "YES", we can just hit 'enter'. that would be convenient

**Comment by balintlaczko** [comment]
Cycling just updated (v8.1.4) the [dialog] object with some nice new modes, including the "Confirmation" mode, which does exactly what [VTMDialog] tried to achieve. Plus it accomplishes this enhancement issue. So I will change [VTMDialog] everywhere to shiny new [dialog]-s.
