### ISSUE TITLE
Write cue file is working on a global level not a per scene level

### ISSUE THREAD

**Issue by salkin-mada** [eirikblekesaune/VTMax#63]
Write cue file safes all global cue data that was stored but not written to files yet.

Open two scenes. Change some stuff in one scene, press store new cue. Be happy with your changes for now. But not wanting to write cue file just yet. 
Then go to the second scene do some stuff, change your favourite spatProxy's pan and width spec. Press store new cue, give it a name. This change however you are certain you want to write to the cue file of that second scene right away. Therefore press write cue, and press YES on the pop up.
Now the stored contents of the not-written cue in the first scene is written to the cue file of the second scene in addition (as expected) to the cue data from the second scene.

**Comment by eirikblekesaune** [comment]
Take a look at the j.cue object. See if 'namespace/unselect /' is done, and
that only the scene namespace is selected: 'namespace/select /mySceneName'

**Comment by salkin-mada** [comment]
this is inputted to j.cue `namespace/unselect /, namespace/select $1`

**Comment by eirikblekesaune** [comment]
What comes in the $1 upon init?

**Comment by salkin-mada** [comment]
the name of the sceneCore ex. `/myScene`

**Comment by salkin-mada** [comment]
on cue store `j.cue` outputs the following to the `route` object:
`names myCue1 testCue someCue cueBugTester tester tester2 tester3`
what is interesting here is that I had another scene open and now my `tester3` cue holds data from the other scene. As described in the OP. But that other scene's name is nowhere to be found in the init namespace to `j.cue`

**Comment by salkin-mada** [comment]
could it be the update cue without recall aka receive `10132_setCurrentCueWithoutRecall` that receives something from the other scene? hmm. I am confused. I have no idea what is going on.

**Comment by eirikblekesaune** [comment]
Ok, so it seems that newly opened patch namespaces are added to scenes
inner j.cue objects. This means that when you make sceneA and store cues,
all is fine. When you make sceneB and store cues all is fine. But then if
you make new cues in sceneA you get the data from sceneB as well. Then if
you create sceneC, sceneA will get both sceneB and sceneC settings in its
cues. SceneB will get only get sceneC and its own sceneB data in its cues.

The culprit is the namespace/selection init in scene core model patch,
which only is set upon init.
Try the uploaded fix in branch fixCueNamespaceBug.

**Comment by eirikblekesaune** [comment]
This one 7b7885b6d2eec5cbbf0d5c65ad36cdba57324fa4

**Comment by salkin-mada** [comment]
bug persists after merging #65 
open 'TestScene' and 'YetAnotherTestScene' from this repo, touch parameters in 'YetAnotherTestScene', go to 'TestScene' touch some things and store a new cue. This new cue in 'TestScene' now holds data from the 'YetAnotherTestScene'.

**Comment by salkin-mada** [comment]
Okay so there something with order of execution going on here.
if i open 'TestScene' and then 'YetAnotherTestScene'. 'TestScene' is the one taking in data from 'YetAnotherTestScene'. If I open 'YetAnotherTestScene' and then 'TestScene', 'YetAnotherTestScene' is the one taking in data from 'TestScene'.

yet = 'YetAnotherTestScene'
test = 'TestScene'

**open yet
open test**
touch yet
touch test -> store
_test is good_
touch test
touch yet -> store
_yet is fucked_

**open yet
open test**
touch test
touch yet -> store
_yet is fucked_
touch yet
touch test -> store
_test is good_

**open test
open yet**
touch yet
touch test -> store
_test is fucked_
touch test
touch yet -> store
_yet is good_

**open test
open yet**
touch test
touch yet -> store
_yet is good_
touch yet
touch test -> store
_test is fucked_

**Comment by salkin-mada** [comment]
pressing the message box (inside the cuehandling subpatcher (namespace) the message going into j.cue) before storing any cues seems to fix the issue.
