### ISSUE TITLE
Make scene set file parser in the scene manager

### ISSUE THREAD

**Issue by eirikblekesaune** [eirikblekesaune/VTMax#7]
A scene set list is a user type data.
Should contain a list of scene paths.

**Comment by balintlaczko** [comment]
Basically done, but there is one necessary improvement yet to be implemented: the set loader script should know whether a scene within the set is already opened or not (so we avoid loading something twice). Loading scenes with "a fresh start" works fine now. Saving also works fine.

**Comment by balintlaczko** [comment]
Okay, now it's good. Before trying to open a scene, it always checks if it is not opened already.
